const SHOWBIGIMG = 'SHOWBIGIMG'
const CLOSEBIGIMG = 'CLOSEBIGIMG'
const CONCATIMGARR = 'CONCATIMGARR'
const SHOWPREV = 'SHOWPREV'
const SHOWNEXT = 'SHOWNEXT'
export {SHOWBIGIMG, CLOSEBIGIMG, CONCATIMGARR, SHOWPREV, SHOWNEXT}
